### ISSUE TITLE
More examples needed

### ISSUE THREAD

**Issue by benmarwick** [mrecos/DistRegLMERR#2] opened 2018-05-18 18:49 UTC
Each exported fn needs an example in its help pages. See my comments here: https://github.com/openjournals/joss-reviews/issues/722#issue-320042175

**Comment by mrecos** [comment] 2019-01-16 20:40
Each exported function has an example. Most are tagged as `\dontrun` but do have fully functional examples. The issue is that to compute the data required as inputs to some function (prediction for example) require a good bit of computing. Closing issue.

**Closed as completed by mrecos** 2019-01-16 20:40 UTC
